import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminApi } from '../api/adminEndpoints';

export function AdminTests() {
  const [tests, setTests] = useState<any[]>([]); const [search, setSearch] = useState(''); const [active, setActive] = useState(''); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ page: 1, pageSize: 25, total: 0, pages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  function refresh() { setLoading(true); setError(null); AdminApi.listTests({ search, active, page, pageSize: 25 }).then((res) => { setTests(res.tests); setPagination(res.pagination); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }
  useEffect(refresh, [search, active, page]);
  async function toggleActive(test: any) { setError(null); setMessage(null); try { await AdminApi.updateTest(test._id, { active: !test.active }); setMessage(`${test.name} is now ${test.active ? 'Inactive' : 'Active'}.`); refresh(); } catch (e: any) { setError(e.message); } }
  async function archive(test: any) { if (!window.confirm(`Hide ${test.name} from the public catalog? Historical results and purchases will be preserved.`)) return; try { await AdminApi.archiveTest(test._id); setMessage('Test hidden from the public catalog.'); refresh(); } catch (e: any) { setError(e.message); } }
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#765c8d]">Products</p><h1 className="mt-1 text-2xl font-semibold text-[#302447]">All tests</h1><p className="mt-2 text-sm text-slate-500">Manage pricing, availability, versions, questions, and results.</p></div><Link to="/admin/tests/new" className="rounded-xl bg-[#765c8d] px-4 py-2.5 text-sm font-semibold text-white">Create test</Link></div><div className="mt-5 flex flex-wrap gap-3"><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search by name or slug" className="admin-input max-w-sm" /><select value={active} onChange={(e) => { setActive(e.target.value); setPage(1); }} className="admin-input w-auto"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div>{message && <p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}{error && <p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{loading ? <p className="mt-5 text-sm text-slate-500">Loading tests...</p> : tests.length === 0 ? <p className="mt-5 rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">No tests found.</p> : <div className="admin-table-wrap mt-5"><table className="w-full text-sm"><thead><tr><th>Name</th><th>Slug</th><th>Status</th><th>Price</th><th>Actions</th></tr></thead><tbody>{tests.map((test) => <tr key={test._id}><td><Link to={`/admin/tests/${test._id}`} className="font-semibold text-[#765c8d] underline underline-offset-4">{test.name}</Link></td><td className="text-slate-500">{test.slug}</td><td><button onClick={() => toggleActive(test)} className={`rounded-full px-2.5 py-1 text-xs font-semibold ${test.active ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{test.active ? 'Active' : 'Inactive'} · click to change</button></td><td>${(test.price.amount / 100).toFixed(2)}</td><td className="space-x-3"><Link to={`/admin/tests/${test._id}`} className="font-semibold text-[#765c8d]">Edit</Link><button onClick={() => archive(test)} className="font-semibold text-red-600">Hide</button></td></tr>)}</tbody></table></div>}<div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{pagination.total} tests</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((v) => v - 1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Previous</button><span className="px-2 py-1.5">Page {pagination.page} of {Math.max(1, pagination.pages)}</span><button disabled={page >= pagination.pages} onClick={() => setPage((v) => v + 1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Next</button></div></div></div>;
}
