import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AdminApi } from '../api/adminEndpoints';

export function AdminAttemptDetail() {
  const { attemptId } = useParams<{ attemptId: string }>(); const [attempt, setAttempt] = useState<any>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (attemptId) AdminApi.getAttempt(attemptId).then((res) => setAttempt(res.attempt)).catch((e) => setError(e.message)); }, [attemptId]);
  if (error) return <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>;
  if (!attempt) return <p className="text-sm text-slate-500">Loading attempt...</p>;
  return <div><Link to="/admin/attempts" className="text-xs font-semibold text-[#765c8d]">← Back to attempts</Link><div className="mt-4 rounded-2xl border border-[#eee5e9] bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#765c8d]">Attempt details</p><h1 className="mt-1 text-2xl font-semibold text-[#302447]">{attempt.testId?.name || 'Test attempt'}</h1><p className="mt-2 text-sm text-slate-500">{attempt.userId?.email || attempt.userId?.username || '-'}</p></div><span className="rounded-full bg-[#f1ebf5] px-3 py-1 text-xs font-semibold text-[#765c8d]">{attempt.status}</span></div><div className="mt-6 grid gap-4 text-sm sm:grid-cols-4"><div><p className="text-xs text-slate-400">Version</p><p className="mt-1 font-semibold">{attempt.testVersionId}</p></div><div><p className="text-xs text-slate-400">Started</p><p className="mt-1 font-semibold">{new Date(attempt.startedAt).toLocaleString()}</p></div><div><p className="text-xs text-slate-400">Completed</p><p className="mt-1 font-semibold">{attempt.completedAt ? new Date(attempt.completedAt).toLocaleString() : '-'}</p></div><div><p className="text-xs text-slate-400">Answers</p><p className="mt-1 font-semibold">{attempt.answers?.length ?? 0}</p></div></div></div>{attempt.result && <section className="mt-5 rounded-2xl border border-[#eee5e9] bg-white p-6 shadow-sm"><h2 className="font-semibold text-[#302447]">Result</h2><p className="mt-2 text-lg font-semibold">{attempt.result.snapshot?.title}</p><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{attempt.result.snapshot?.description}</p><p className="mt-3 text-xs text-slate-500">Result key: {attempt.result.resultKey}</p><pre className="mt-4 overflow-auto rounded-xl bg-slate-50 p-4 text-xs">{JSON.stringify({ rawScores: attempt.result.rawScores, categoryScores: attempt.result.categoryScores }, null, 2)}</pre></section>}<section className="mt-5 rounded-2xl border border-[#eee5e9] bg-white p-6 shadow-sm"><h2 className="font-semibold text-[#302447]">Submitted answers</h2><div className="mt-3 space-y-2">{(attempt.answers || []).map((answer: any, index: number) => <div key={`${answer.questionId}-${index}`} className="rounded-xl bg-slate-50 p-3 text-sm"><b>#{index + 1}</b><span className="ml-3 text-slate-600">Question: {answer.questionId} · Option: {answer.answerOptionId}</span></div>)}</div></section></div>;
}
