import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminApi } from '../api/adminEndpoints';

type Overview = { stats: { users: number; activeUsers: number; newUsers: number; tests: number; activeTests: number; draftVersions: number; publishedVersions: number; orders: number; successfulPayments: number; failedPayments: number; revenue: number }; recentUsers: any[]; recentOrders: any[]; recentAttempts: any[] };

export function AdminDashboard() {
  const [data, setData] = useState<Overview | null>(null);
  const [tests, setTests] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { Promise.all([AdminApi.overview(), AdminApi.listTests()]).then(([overview, testRes]) => { setData(overview); setTests(testRes.tests); }).catch((e) => setError(e.message)); }, []);
  const filtered = tests.filter((test) => `${test.name} ${test.slug}`.toLowerCase().includes(search.toLowerCase()));
  const stats = data?.stats;
  const cards = [['Users', stats?.users ?? '—', 'bg-[#f0ebf8] text-[#765c8d]'], ['Active users', stats?.activeUsers ?? '—', 'bg-[#edf7f1] text-[#4c9a83]'], ['New users (30d)', stats?.newUsers ?? '—', 'bg-[#eef4ff] text-[#607fb2]'], ['Tests', stats?.tests ?? '—', 'bg-[#eef4ff] text-[#607fb2]'], ['Published versions', stats?.publishedVersions ?? '—', 'bg-[#edf7f1] text-[#4c9a83]'], ['Draft versions', stats?.draftVersions ?? '—', 'bg-[#fff3e5] text-[#b47a35]'], ['Orders', stats?.orders ?? '—', 'bg-[#fff3e5] text-[#b47a35]'], ['Paid orders', stats?.successfulPayments ?? '—', 'bg-[#edf7f1] text-[#4c9a83]'], ['Failed orders', stats?.failedPayments ?? '—', 'bg-[#fff0f0] text-[#bd5f6f]'], ['Revenue', stats ? `$${(stats.revenue / 100).toFixed(2)}` : '—', 'bg-[#f5edf1] text-[#bd7891]']];

  return <div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value, tone]) => <div key={label} className="admin-stat"><span className={`admin-stat-icon ${tone}`}>●</span><div><p className="text-xs text-slate-400">{label}</p><p className="text-2xl font-semibold text-[#302447]">{value}</p></div></div>)}</div>{error && <p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    <div className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#eee5e9] bg-white p-5 shadow-sm"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#765c8d]">Test workspace</p><h2 className="mt-1 text-xl font-semibold text-[#302447]">Manage your assessments</h2><p className="mt-1 text-sm text-slate-500">Create a complete test from its own detailed builder page.</p></div><Link to="/admin/tests/new" className="rounded-xl bg-[#765c8d] px-5 py-3 text-sm font-semibold text-white">Create complete test</Link></div>
    <section className="admin-table-wrap mt-5"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#f1ebf0] p-5"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#765c8d]">Products</p><h2 className="mt-1 text-xl font-semibold text-[#302447]">Tests</h2></div><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search tests..." className="rounded-lg border border-[#e5dce8] px-3 py-2 text-sm outline-none" /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Name</th><th>Status</th><th>Price</th><th /></tr></thead><tbody>{filtered.map((test) => <tr key={test._id}><td>{test.name}<small className="block text-xs text-slate-400">{test.slug}</small></td><td><span className={`rounded-full px-2 py-1 text-xs ${test.active ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{test.active ? 'Active' : 'Inactive'}</span></td><td>${(test.price.amount / 100).toFixed(2)}</td><td><Link to={`/admin/tests/${test._id}`} className="font-semibold text-[#765c8d]">Manage</Link></td></tr>)}</tbody></table></div></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-[#eee5e9] bg-white p-5 shadow-sm"><h2 className="font-semibold text-[#302447]">Recent users</h2>{data?.recentUsers.map((user) => <div key={user._id} className="mt-3 flex justify-between border-b border-[#f1ebf0] pb-3 text-sm"><span>{user.username || user.email || user.phone}</span><span className="text-xs text-slate-400">{new Date(user.createdAt).toLocaleDateString()}</span></div>)}</section><section className="rounded-2xl border border-[#eee5e9] bg-white p-5 shadow-sm"><h2 className="font-semibold text-[#302447]">Recent orders</h2>{data?.recentOrders.map((order) => <div key={order._id} className="mt-3 flex justify-between border-b border-[#f1ebf0] pb-3 text-sm"><span>{order.testId?.name || 'Test'}</span><span className="text-xs text-slate-400">{order.status} · ${(order.amount / 100).toFixed(2)}</span></div>)}</section></div>
  </div>;
}
