import { useEffect, useState } from 'react';
import { AdminApi } from '../api/adminEndpoints';

export function AdminAnalytics() {
  const [data, setData] = useState<any>(null); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  function load() { setLoading(true); setError(null); AdminApi.analytics({ from: from || undefined, to: to || undefined }).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)); }
  useEffect(load, []);
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#765c8d]">Business intelligence</p><h1 className="mt-1 text-2xl font-semibold text-[#302447]">Analytics</h1></div><div className="flex flex-wrap gap-2"><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="admin-input" /><input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="admin-input" /><button onClick={load} className="rounded-xl bg-[#765c8d] px-4 py-2 text-sm font-semibold text-white">Apply</button></div></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading ? <p className="mt-5 text-sm text-slate-500">Loading analytics...</p> : data && <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="admin-table-wrap p-5"><h2 className="font-semibold text-[#302447]">Paid purchases by day</h2><table className="mt-4 w-full text-sm"><thead><tr><th className="text-left">Date</th><th className="text-right">Purchases</th><th className="text-right">Revenue</th></tr></thead><tbody>{data.dailyPurchases.map((row: any) => <tr key={row._id} className="border-t border-slate-100"><td className="py-2">{row._id}</td><td className="text-right">{row.purchases}</td><td className="text-right">${(row.revenue / 100).toFixed(2)}</td></tr>)}</tbody></table>{data.dailyPurchases.length === 0 && <p className="mt-4 text-sm text-slate-500">No paid purchases in this period.</p>}</section><section className="admin-table-wrap p-5"><h2 className="font-semibold text-[#302447]">Revenue by test</h2><table className="mt-4 w-full text-sm"><thead><tr><th className="text-left">Test</th><th className="text-right">Purchases</th><th className="text-right">Revenue</th></tr></thead><tbody>{data.byTest.map((row: any) => <tr key={row._id} className="border-t border-slate-100"><td className="py-2">{row.name || 'Unknown test'}</td><td className="text-right">{row.purchases}</td><td className="text-right">${(row.revenue / 100).toFixed(2)}</td></tr>)}</tbody></table></section><section className="admin-table-wrap p-5"><h2 className="font-semibold text-[#302447]">Activity</h2><p className="mt-3 text-sm text-slate-600">New users: <b>{data.newUsers}</b></p>{data.attempts.map((row: any) => <p key={row._id} className="mt-2 text-sm text-slate-600">Attempts ({row._id}): <b>{row.count}</b></p>)}</section><section className="admin-table-wrap p-5"><h2 className="font-semibold text-[#302447]">Marketing delivery</h2>{data.marketing.map((row: any) => <p key={row._id} className="mt-3 text-sm text-slate-600">{row._id}: <b>{row.count}</b></p>)}{data.marketing.length === 0 && <p className="mt-3 text-sm text-slate-500">No marketing deliveries in this period.</p>}</section></div>}</div>;
}
