import { useEffect, useState } from 'react';
import { AdminApi } from '../api/adminEndpoints';

export function AdminPurchases() {
  const [purchases, setPurchases] = useState<any[]>([]); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ page: 1, pageSize: 25, total: 0, pages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = () => { setLoading(true); setError(null); AdminApi.listPurchases({ status, page, pageSize: 25 }).then((res) => { setPurchases(res.purchases); setPagination(res.pagination); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, [status, page]);
  return <div><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold text-slate-900">Orders & Payments</h1><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="admin-input max-w-xs"><option value="">All statuses</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="capturing">Capturing</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></div>{error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading ? <p className="mt-5 text-sm text-slate-500">Loading orders...</p> : purchases.length === 0 ? <p className="mt-5 rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">No purchases found.</p> : <div className="admin-table-wrap mt-4"><table className="w-full text-sm"><thead><tr className="border-b border-slate-200 text-left text-slate-500"><th className="py-2">Status</th><th>Customer</th><th>Test</th><th>Amount</th><th>Currency</th><th>PayPal order</th><th>Created</th></tr></thead><tbody>{purchases.map((p) => <tr key={p._id} className="border-b border-slate-100"><td className="py-2">{p.status}</td><td>{p.userId?.email || p.userId?.username || '-'}</td><td>{p.testId?.name || '-'}</td><td>${(p.amount / 100).toFixed(2)}</td><td>{p.currency?.toUpperCase()}</td><td className="max-w-[200px] truncate">{p.paypalOrderId}</td><td>{new Date(p.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}<div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{pagination.total} purchases</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((current) => current - 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Previous</button><span className="px-2 py-1.5">Page {pagination.page} of {Math.max(1, pagination.pages)}</span><button disabled={page >= pagination.pages} onClick={() => setPage((current) => current + 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Next</button></div></div></div>;
}
