import { useEffect, useState } from 'react';
import { AdminApi } from '../api/adminEndpoints';

export function AdminAuditLogs() {
  const [logs, setLogs] = useState<any[]>([]); const [action, setAction] = useState(''); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ page: 1, pageSize: 25, total: 0, pages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = () => { setLoading(true); setError(null); AdminApi.listAuditLogs({ action, page, pageSize: 25 }).then((res) => { setLogs(res.logs); setPagination(res.pagination); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, [action, page]);
  return <div><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold text-slate-900">Audit logs</h1><input value={action} onChange={(e) => { setAction(e.target.value); setPage(1); }} placeholder="Filter action" className="admin-input max-w-xs" /></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading ? <p className="mt-4 text-sm text-slate-500">Loading audit logs...</p> : logs.length === 0 ? <p className="mt-4 rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">No audit logs found.</p> : <div className="admin-table-wrap mt-4"><table className="w-full text-sm"><thead><tr className="border-b border-slate-200 text-left text-slate-500"><th className="py-2">Time</th><th>Admin</th><th>Action</th><th>Entity</th><th>Status</th><th>IP</th></tr></thead><tbody>{logs.map((log) => <tr key={log._id} className="border-b border-slate-100"><td className="py-2">{new Date(log.createdAt).toLocaleString()}</td><td>{log.actorId?.email || log.actorId?.username || '-'}</td><td>{log.action}</td><td>{log.entityType}{log.entityId ? `/${log.entityId}` : ''}</td><td>{log.statusCode}</td><td>{log.ip || '-'}</td></tr>)}</tbody></table></div>}<div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{pagination.total} events</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((current) => current - 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Previous</button><span>Page {pagination.page} of {Math.max(1, pagination.pages)}</span><button disabled={page >= pagination.pages} onClick={() => setPage((current) => current + 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Next</button></div></div></div>;
}
