import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AdminApi } from '../api/adminEndpoints';

const emptyForm = { resultKey: '', imageUrl: '', minScore: '', maxScore: '', title: '', description: '', strengths: '', challenges: '', communication: '', relationships: '', recommendations: '' };

export function ResultEditor() {
  const { versionId } = useParams<{ versionId: string }>();
  const [results, setResults] = useState<any[]>([]);
  const [form, setForm] = useState(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  function refresh() { if (versionId) AdminApi.listResults(versionId).then((res) => setResults(res.results)).catch((e) => setError(e.message)); }
  useEffect(refresh, [versionId]);
  function edit(result: any) { setEditingId(result._id); setForm({ resultKey: result.resultKey ?? '', imageUrl: result.imageUrl ?? '', minScore: result.minScore ?? '', maxScore: result.maxScore ?? '', title: result.title ?? '', description: result.description ?? '', strengths: result.strengths ?? '', challenges: result.challenges ?? '', communication: result.communication ?? '', relationships: result.relationships ?? '', recommendations: result.recommendations ?? '' }); }
  function reset() { setEditingId(null); setForm(emptyForm); }
  async function handleSave() { if (!versionId || !form.resultKey.trim() || !form.title.trim() || !form.description.trim()) { setError('Result key, title, and description are required.'); return; } setError(null); setMessage(null); try { await AdminApi.upsertResult({ testVersionId: versionId, ...form, minScore: form.minScore === '' ? null : Number(form.minScore), maxScore: form.maxScore === '' ? null : Number(form.maxScore) }); setMessage(editingId ? 'Result updated.' : 'Result added.'); reset(); refresh(); } catch (e: any) { setError(e.message); } }
  async function remove(result: any) { if (!window.confirm(`Delete result ${result.title}?`)) return; try { await AdminApi.deleteResult(result._id); setMessage('Result deleted.'); refresh(); } catch (e: any) { setError(e.message); } }
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));

  return <div><div className="flex flex-wrap items-start justify-between gap-3"><div><Link to="-1" onClick={(event) => { event.preventDefault(); window.history.back(); }} className="text-xs font-semibold text-[#765c8d]">← Back</Link><h1 className="mt-3 text-xl font-semibold text-[#302447]">Result definitions</h1><p className="mt-1 text-sm text-slate-500">Create the complete result content customers see after finishing this version.</p></div>{editingId && <button onClick={reset} className="text-xs text-slate-500">Cancel edit</button>}</div>{error && <p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message && <p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}
    <section className="mt-5 rounded-2xl border border-[#eee5e9] bg-white p-5 shadow-sm"><h2 className="font-semibold text-[#302447]">{editingId ? 'Edit result' : 'Add result'}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="admin-field">Result key<input value={form.resultKey} onChange={(e) => update('resultKey', e.target.value)} className="admin-input" placeholder="INFJ or SECURE" disabled={Boolean(editingId)} /></label><label className="admin-field">Title<input value={form.title} onChange={(e) => update('title', e.target.value)} className="admin-input" /></label><label className="admin-field">Minimum score<input type="number" value={form.minScore} onChange={(e) => update('minScore', e.target.value)} className="admin-input" /></label><label className="admin-field">Maximum score<input type="number" value={form.maxScore} onChange={(e) => update('maxScore', e.target.value)} className="admin-input" /></label><label className="admin-field sm:col-span-2">Result image URL<input value={form.imageUrl} onChange={(e) => update('imageUrl', e.target.value)} className="admin-input" placeholder="https://... or /test-results/result.png" /></label><label className="admin-field sm:col-span-2">Description<textarea value={form.description} onChange={(e) => update('description', e.target.value)} className="admin-input min-h-24" /></label><label className="admin-field">Strengths<textarea value={form.strengths} onChange={(e) => update('strengths', e.target.value)} className="admin-input min-h-24" /></label><label className="admin-field">Challenges<textarea value={form.challenges} onChange={(e) => update('challenges', e.target.value)} className="admin-input min-h-24" /></label><label className="admin-field">Communication<textarea value={form.communication} onChange={(e) => update('communication', e.target.value)} className="admin-input min-h-24" /></label><label className="admin-field">Relationships<textarea value={form.relationships} onChange={(e) => update('relationships', e.target.value)} className="admin-input min-h-24" /></label><label className="admin-field sm:col-span-2">Recommendations<textarea value={form.recommendations} onChange={(e) => update('recommendations', e.target.value)} className="admin-input min-h-24" /></label></div><button onClick={handleSave} className="mt-4 rounded-xl bg-[#765c8d] px-5 py-2.5 text-sm font-semibold text-white">{editingId ? 'Save result' : 'Add result'}</button></section>
    <section className="mt-6"><h2 className="font-semibold text-[#302447]">Saved results ({results.length})</h2><div className="mt-3 space-y-3">{results.map((result) => <article key={result._id} className="rounded-2xl border border-[#eee5e9] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#765c8d]">{result.resultKey} · {result.minScore ?? '—'} to {result.maxScore ?? '—'}</p><h3 className="mt-1 font-semibold text-[#302447]">{result.title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{result.description}</p></div><div className="flex shrink-0 gap-2"><button onClick={() => edit(result)} className="rounded-lg bg-[#f1ebf5] px-3 py-2 text-xs font-semibold text-[#765c8d]">Edit</button><button onClick={() => remove(result)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-600">Delete</button></div></div></article>)}</div></section>
  </div>;
}
