import { FormEvent, useState } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import { AuthApi } from '../api/endpoints';
import { ApiError } from '../api/client';
import { PasswordVisibilityIcon } from '../components/PasswordVisibilityIcon';

export function ResetPassword() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const token = params.get('token') ?? ''; const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [visible, setVisible] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); if (password !== confirm) { setError('Passwords do not match.'); return; } setLoading(true); try { await AuthApi.resetPassword(token, password); setDone(true); setTimeout(() => navigate('/login'), 1200); } catch (err) { setError(err instanceof ApiError ? err.message : 'This reset link is invalid or expired.'); } finally { setLoading(false); } }
  return <div className="min-h-[calc(100vh-74px)] bg-[#f7f3f2] px-4 py-10 sm:px-8"><div className="mx-auto max-w-md rounded-[2rem] border border-white bg-[#fffdfb] p-7 shadow-xl sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#765c8d]">Account recovery</p><h1 className="mt-3 text-3xl font-semibold text-[#302447]">Reset your password</h1>{!token ? <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">This reset link is invalid or expired.</p> : done ? <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Password updated. Redirecting to login...</p> : <form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-medium text-[#302447]">New password<div className="relative mt-2"><input type={visible ? 'text' : 'password'} required minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} className="w-full rounded-xl border border-[#d9cfdb] bg-white px-4 py-3.5 pr-12 outline-none focus:border-[#765c8d]" /><button type="button" onClick={() => setVisible(!visible)} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#765c8d]"><PasswordVisibilityIcon visible={visible} /></button></div></label><label className="block text-sm font-medium text-[#302447]">Confirm password<input type={visible ? 'text' : 'password'} required minLength={8} value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d9cfdb] bg-white px-4 py-3.5 outline-none focus:border-[#765c8d]" /></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-[#765c8d] py-3.5 text-sm font-semibold text-white disabled:opacity-50">{loading ? 'Updating...' : 'Update password'}</button></form>}<Link to="/login" className="mt-6 block text-center text-sm font-semibold text-[#765c8d]">Back to login</Link></div></div>;
}
