const sections = [
  ['1. About Our Services', 'My Inner provides online self-assessment tests and related informational content, including personality, relationship, preferences, communication, and other self-discovery tests.\n\nThe tests are provided for informational, educational, and entertainment purposes only. They are not intended to provide professional psychological, medical, psychiatric, legal, financial, or other professional advice.\n\nTest results should not be considered a diagnosis, professional assessment, or definitive statement about your personality, behavior, relationships, or abilities.'],
  ['2. Use of the Website', 'You agree to use My Inner only for lawful purposes and in accordance with these Terms.\n\nYou must not:\n• Use the website for any unlawful or fraudulent purpose.\n• Attempt to gain unauthorized access to the website or its systems.\n• Interfere with the operation or security of the website.\n• Copy, reproduce, distribute, or commercially exploit website content without permission.\n• Attempt to modify, reverse engineer, or extract the website’s software, algorithms, or test systems.\n• Use automated systems, bots, scraping tools, or similar technologies to collect website content without our written permission.\n• Submit false, misleading, or fraudulent information where information is required.\n\nWe reserve the right to restrict or terminate access to users who violate these Terms.'],
  ['3. Test Results', 'Test results are generated based on the answers provided by the user and the scoring methodology used by the relevant test. Results are intended to provide general insights and should not be treated as absolute or scientifically definitive conclusions about an individual. Different answers, circumstances, interpretations, or testing methodologies may produce different results. You are responsible for how you interpret and use your results.'],
  ['4. No Professional Advice', 'The information and results provided through My Inner do not constitute professional advice. In particular, our tests should not be used as a substitute for medical or mental-health evaluation, psychological assessment by a qualified professional, professional relationship or counseling services, legal advice, financial advice, or employment or recruitment assessments conducted by qualified professionals. If you require professional advice, you should consult an appropriately qualified professional.'],
  ['5. Intellectual Property', 'Unless otherwise stated, all content available on My Inner, including website design, branding, text, test questions, test structures, scoring systems, graphics, illustrations, results descriptions, software, and functionality, is owned by or licensed to My Inner and is protected by applicable intellectual-property laws. You may use the website and its content for your personal, non-commercial purposes only.'],
  ['6. User-Generated Information', 'When you submit answers, information, comments, feedback, or other content through the website, you are responsible for ensuring that the information you provide is accurate and lawful. You agree not to submit content that is illegal, harmful, abusive, defamatory, or infringes upon the rights of others.'],
  ['7. Privacy', 'Your use of My Inner is also subject to our Privacy Policy, which explains how information submitted through the website may be collected, used, stored, and protected. By using the website, you acknowledge that you have read and understood our Privacy Policy.'],
  ['8. Cookies and Similar Technologies', 'My Inner may use cookies and similar technologies to operate the website, remember preferences, understand website usage, and improve our services. Where required by applicable law, we will request appropriate consent before using non-essential cookies.'],
  ['9. Third-Party Services and Links', 'The website may contain links to third-party websites, services, advertisements, or tools. We do not control and are not responsible for the content, availability, security, privacy practices, or terms of third-party websites. Accessing third-party websites is done at your own risk and is subject to their respective terms and policies.'],
  ['10. Website Availability', 'We aim to keep My Inner available and functioning properly. However, we do not guarantee that the website will always be available, uninterrupted, secure, or error-free. We may temporarily suspend, modify, update, or discontinue any part of the website without prior notice where reasonably necessary.'],
  ['11. Accuracy of Information', 'We make reasonable efforts to provide accurate and useful information. However, we do not guarantee that all information, test descriptions, results, or other content on the website will always be complete, accurate, current, or error-free. We reserve the right to update or modify website content at any time.'],
  ['12. Limitation of Liability', 'To the maximum extent permitted by applicable law, My Inner and its owners, employees, affiliates, partners, and service providers shall not be liable for any direct, indirect, incidental, consequential, or other losses arising from or related to your use or inability to use the website, your reliance on test results or website content, errors or inaccuracies in test results, website interruptions or technical problems, third-party websites or services, or decisions made based on information obtained through the website. Nothing in these Terms excludes or limits liability where such exclusion or limitation is prohibited by applicable law.'],
  ['13. Indemnification', 'You agree to indemnify and hold harmless My Inner, its owners, employees, affiliates, and service providers from claims, losses, liabilities, damages, and expenses arising from your violation of these Terms or misuse of the website.'],
  ['14. Changes to These Terms', 'We may update these Terms & Conditions from time to time. When changes are made, the updated version will be posted on this page together with the revised “Last Updated” date. Your continued use of the website after changes are posted constitutes acceptance of the updated Terms.'],
  ['15. Termination', 'We reserve the right to suspend or terminate access to the website, without prior notice where appropriate, if we believe that a user has violated these Terms, misused the website, or engaged in activities that may harm the website, its users, or its services.'],
  ['16. Governing Law', 'These Terms & Conditions shall be governed by and interpreted in accordance with the laws applicable in [Country/Jurisdiction], unless otherwise required by applicable law. Any disputes arising in connection with these Terms shall be subject to the jurisdiction of the competent courts of [Jurisdiction], unless applicable law provides otherwise.'],
  ['17. Contact Us', 'If you have questions regarding these Terms & Conditions, please contact us at admin@my-inner.com.']
];

export function Terms() {
  return <main className="min-h-[calc(100vh-74px)] bg-[#fffdfb] px-5 py-12 sm:px-8 lg:py-16"><article className="mx-auto max-w-4xl rounded-3xl border border-[#eee5e9] bg-white px-6 py-8 shadow-sm sm:px-10 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#765c8d]">My Inner</p><h1 className="mt-3 font-serif text-4xl text-[#283452] sm:text-5xl">Terms &amp; Conditions</h1><p className="mt-6 leading-7 text-[#5e6170]">Welcome to My Inner. These Terms &amp; Conditions govern your use of our website, services, tests, results, content, and related features. By accessing or using My Inner, you agree to be bound by these Terms &amp; Conditions.</p><p className="mt-3 leading-7 text-[#5e6170]">If you do not agree with any part of these terms, please do not use the website.</p>{sections.map(([title, body]) => <section key={title} className="mt-9"><h2 className="text-xl font-semibold text-[#302447]">{title}</h2><div className="mt-3 whitespace-pre-line leading-7 text-[#5e6170]">{body}</div></section>)}<p className="mt-10 border-t border-[#eee5e9] pt-6 font-medium leading-7 text-[#302447]">By using My Inner, you acknowledge that you have read, understood, and agreed to these Terms &amp; Conditions.</p></article></main>;
}
