import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { TestsApi } from '../api/endpoints';
import { LoadingScreen } from '../components/LoadingScreen';
import { PublicTest } from '../types';
import { TestIcon, testIconTone } from '../components/TestIcon';

export function TestCatalog() {
  const [tests, setTests] = useState<PublicTest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { TestsApi.list().then((res) => setTests(res.tests)).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  if (loading) return <LoadingScreen message="Finding your next reflection..." detail="We’re gathering the assessments for you." />;
  if (error) return <div className="p-8 text-center text-red-600">{error}</div>;
  return <div className="tests-page min-h-[calc(100vh-74px)] px-4 py-12 sm:px-8 sm:py-16"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#765c8d]">Explore inward</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-[#302447] sm:text-5xl">Find a test that feels like you.</h1><p className="mt-4 text-base leading-7 text-slate-500">Take a moment to reflect, answer at your own pace, and discover a clearer way to understand yourself.</p></div>{tests.length === 0 ? <p className="mt-10 text-center text-slate-500">No tests are available yet. Check back soon.</p> : <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{tests.map((test) => <Link key={test.id} to={`/tests/${test.slug}`} className="test-card group relative overflow-hidden rounded-[1.5rem] border border-[#eee7ed] bg-white p-6 shadow-[0_8px_24px_rgba(73,57,88,0.05)] transition hover:-translate-y-1 hover:shadow-xl hover:shadow-[#765c8d]/10"><div className={`flex h-16 w-16 items-center justify-center rounded-2xl ${testIconTone(test.slug)}`}><TestIcon slug={test.slug} className="h-9 w-9" /></div><span className={`absolute right-5 top-5 rounded-full px-3 py-1 text-[10px] font-semibold ${test.available ? 'bg-[#edf7f1] text-[#4c9a83]' : 'bg-[#fff6e9] text-[#b47a35]'}`}>{test.available ? 'Available' : 'Coming soon'}</span><h2 className="mt-6 min-h-12 text-lg font-semibold leading-6 text-[#302447]">{test.name}</h2><p className="mt-3 line-clamp-3 min-h-[4.5rem] text-sm leading-6 text-slate-500">{test.description}</p><div className="mt-6 flex items-center justify-between border-t border-[#f1ebf0] pt-4"><span className="text-sm font-semibold text-[#302447]">${(test.price.amount / 100).toFixed(2)} <small className="font-normal text-slate-400">one-time</small></span><span className="text-sm font-semibold text-[#765c8d] transition group-hover:translate-x-1">Explore →</span></div></Link>)}</div>}<div className="mx-auto mt-14 max-w-3xl rounded-3xl border border-[#eee5e9] bg-[#faf5f8] p-6 text-center sm:p-8"><p className="text-sm font-semibold text-[#302447]">A little curiosity can go a long way.</p><p className="mt-2 text-sm leading-6 text-slate-500">Each assessment is designed as a gentle starting point for self-reflection — not a diagnosis.</p></div></div></div>;
}
